FROM alpine:3.14

RUN apk add --no-cache curl \
    && apk add bash \
    && sh -ci "$(curl -fsSL https://storage.googleapis.com/flow-cli/install.sh)"

ENV PATH "$PATH:/root/.local/bin"

WORKDIR /emulator
COPY flow.local.json ./flow.json
EXPOSE 8080 3569
CMD flow emulator start 


