FROM node:14-alpine

WORKDIR /api
RUN npm install typescript
COPY ./api .
COPY ./cadence /cadence
EXPOSE 3001
CMD npm run dev


# Alternatively, you can use the following Dockerfile to build the API image. 
# Note: You neeed to run the api build to create the /dist folder.

# FROM node:14-alpine
# WORKDIR /api
# COPY ./api/dist ./src
# COPY ./api/node_modules ./node_modules
# COPY ./cadence /cadence
# EXPOSE 3000
# CMD node ./src/index.js && node ./src/index.js --worker

