# FROM node:14-alpine
# WORKDIR /api
# COPY ./api/dist ./src
# COPY ./api/node_modules ./node_modules
# COPY ./cadence /cadence
# EXPOSE 3000
# CMD node ./src/index.js --dev

FROM node:14-alpine

WORKDIR /api
RUN npm install typescript
COPY ./api .
COPY ./cadence /cadence
EXPOSE 3001
CMD export FLOW_ACCESS_API_URL=http://emulator:8080 && npm run dev

